### ISSUE TITLE
Axon: Simple Tests: Test StringProperty failed, ReferenceError: phet is not defined

### ISSUE THREAD

**Issue by phet-steele** [phetsims/axon#162]
Scenery, Kite, and Dot are failing unit tests with:

```
scenery : unit-tests : require.js
5187 out of 5188 tests passed. 1 failed.
Axon: Simple Tests: Test StringProperty failed:
Died on test #2     at https://bayes.colorado.edu/continuous-testing/snapshot-1509384984366/axon/tests/qunit/js/simple-tests.js?random=0.9278429219:307:3
    at https://bayes.colorado.edu/continuous-testing/snapshot-1509384984366/axon/tests/qunit/js/simple-tests.js?random=0.9278429219:346:3: phet is not defined
ReferenceError: phet is not defined
    at Object.<anonymous> (https://bayes.colorado.edu/continuous-testing/snapshot-1509384984366/axon/tests/qunit/js/simple-tests.js?random=0.9278429219:318:5)

```

**Comment by jonathanolson** [comment]
I pushed a fix, @samreid can you verify?

**Comment by pixelzoom** [comment]
I pushed a fix that's a bit cleaner, @samreid please verify.

**Comment by pixelzoom** [comment]
Problem was introduced in #156, fixed once in #161, apparently still not dead.

**Comment by jonathanolson** [comment]
> I pushed a fix that's a bit cleaner, @samreid please verify.

Seems like that fix is for https://github.com/phetsims/axon/issues/161?

**Comment by jonathanolson** [comment]
Typically this would be solved by removing the assignment to p (and adding the code comment to ignore the "no-new" lint rule).

**Comment by pixelzoom** [comment]
@jonathanolson said:
> Seems like that fix is for #161?

Indeed, that hack was added for #161 - an issue I discovered after the fact by looking through commit history.

> Typically this would be solved by removing the assignment to p (and adding the code comment to ignore the "no-new" lint rule).

Agreed.  But since `p` is used throughout all the tests above the one that was failing lint, I chose to make the failing one follow the same pattern.

**Comment by samreid** [comment]
phet.axon => axon fix and `p = ...` fixes both look good, closing.
