### ISSUE TITLE
detect Property loops

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/axon#179]
A Property loop occurs when a Property's `set` method is entered before a previous call to `set` exits.   PhET-iO makes it necessary to deal with these loops because it results in intermediate/redundant data in the message stream.  See for example https://github.com/phetsims/hookes-law/issues/52. 

PhetioObject previously was responsible for detecting Property loops, but that was removed in https://github.com/phetsims/tandem/issues/57.   And I believe it was @samreid who suggested that this responsibility does not belong in PhET-iO; it belongs in axon.  

In https://github.com/phetsims/tandem/issues/57#issuecomment-396712827, I suggested a way to add responsibility (conditionally) to Property, reproduced below.  And I found this to be invaluable in troubleshooting https://github.com/phetsims/hookes-law/issues/52.    I'd like to see this added to Property. 

```js
      // @private
      _notifyListeners: function( oldValue ) {

        // We must short circuit based on tandem here as a guard against the toStateObject calls
        this.tandem.isSuppliedAndEnabled() && this.startEvent( 'model', 'changed', {
          oldValue: this.phetioType.elementType.toStateObject( oldValue ),
          newValue: this.phetioType.elementType.toStateObject( this.get() ),
          units: this.phetioType && this.phetioType.units
        }, this.changeEventOptions );

        // notify listeners, optionally detect loops where this Property is set again before this completes.
        assert && assert( !this.notifying || !phet.chipper.queryParameters.detectPropertyLoops, 
          'Property loop detected, value=' + this.get() + ', oldValue=' + oldValue );
        this.notifying = true;
        this.changedEmitter.emit2( this.get(), oldValue );
        this.notifying = false;

        this.tandem.isSuppliedAndEnabled() && this.endEvent();
      },
````

**Comment by jbphet** [comment]
Seems like a good idea to me.  I've accidentally set up property loop a number of times, and they often ended up locking up the tab due to recursion.  This would have caught the problems earlier and more elegantly.

**Comment by zepumph** [comment]
This was talked about int he meeting today, but only briefly. I am wondering if we could have a property option that dictates whether or not you want to allow `Property.set()` re-entrance. I would prefer that to a global that you toggle for everything in a sim at once.  I think ideally we would want everything to default to not being re-entrant, such that you have to specify `allowReentrantSetting: true` for instances that you want to opt in. Since there are many places in the code where that would break with a default of `false`, perhaps we should go with something else, or use the query parameter until those places have been chipped away.

**Comment by samreid** [comment]
I think we should add `{reentrant: false}` as the default for Property.js, with an assertion error when a loop is detected.  We would quickly "chip-away" and add `reentrant: true` for all the errors that immediately pop up.

**Comment by pixelzoom** [comment]
So... 

Add this to options:

```js
  // {boolean} i
  // true: reentrant calls to `set` fail an assertion
  // false: reentrant calls to `set`are allowed
  detectRentry: true
```

... change assertion in `_notifyListeners` to:

```js
 assert && assert( !this.notifying || !options. detectRentry, 
  'Property loop detected, value=' + this.get() + ', oldValue=' + oldValue );
```

... and deal with assertion failures as they occur in CT (which is sure to be immediately).

Objections?

**Comment by pixelzoom** [comment]
`reentrant` is fine with me.

**Comment by pixelzoom** [comment]
Unless someone else needs this feature for debugging, it might be devisable to defer until I return from vacation.

**Comment by samreid** [comment]
It seems it would be good to have several developers "on hand" when we flip the switch for this, so responsible developers can catch their own `reentrant` Properties.

**Comment by jessegreenberg** [comment]
Discussed at 6/21/18 - 

We will add https://github.com/phetsims/axon/issues/179#issuecomment-397700846 in a branch, then work on it when developers are available all at once. This will probably be done during core hours. We will do it in a branch so that CT continues to run and we can continue to work in common code in case this can't be fixed quickly. I will create a reminder to do this on July 9th since that is when devs will be back in town.

**Comment by pixelzoom** [comment]
On 7/9, @jessegreenberg reminded us about this issue on Slack.

Unless someone else needs it, I would lobby for doing this work after EqEx is in RC, and after I return from vacation, so that I can address my sims.  EqEx RC will start Wed 7/18 at the latest.  I’ll be on vacation 7/19-8/5.

**Comment by jessegreenberg** [comment]
More summarized discussion from slack:

Since we will do this on a branch in axon, devs don't all need to be available to work on this at once. We will wait to work on this issue until priority goes up when it is required in Hooke's Law or somewhere else, and sometime after 8/5.

**Comment by pixelzoom** [comment]
I'm back to working on Hooke's Law PhET-iO, and could really use this to troubleshoot https://github.com/phetsims/hookes-law/issues/52.  So I'm going to resume work on this.

**Comment by pixelzoom** [comment]
Support for this pushed in the above commit.  New option `reentrant` determines whether reentrant calls to `set` are allowed.  It’s default is currently `true`, but we should (re)discuss the value/impact of making this `false`.

**Comment by pixelzoom** [comment]
@zepumph has been randomly selected to review my work.

**Comment by zepumph** [comment]
That looks good to me. At first I was surprised that it would be an assertion rather than just a noop, but I think that is smart. Back to you.

**Comment by pixelzoom** [comment]
After using this to identify cycles in phetsims/hookes-law#52, I'm inclined to leave the default as `reentrant: true`, and use this as a tool to identify cycles, not a requirement that all sims should be cycle-free.  For example, there are corner cases in Hooke's Law where floating-point error causes a values' range to be exceeded, and there's not much choice other than to clamp to the range and cause a cycle.

**Comment by samreid** [comment]
Why not put the default as `reentrant: false` so that all of the re-entrant Properties must be labeled as such.  How did you identify cycles if the default is `reentrant: false`?  Or were you imagining a temporary code change in axon during testing?

**Comment by samreid** [comment]
I temporarily set Property.options.reentrant to default to false and ran a set of fuzz testing.  I observed that the vast majority of property instances do not have a problem with reentrance.  I saw 3 patterns for values that did have a problem with reentrance, here are examples of each of the three types:
```
value=0.9999999999999998, oldValue=1 // epsilon problem
value=-0.4277580409572783, oldValue=-0.5 // large delta problem
value=[Object], oldValue=[Object] // object changed to object problem.  May be same object?
```
Part of the documentation for Property.options.reentrant is:

> Update cycles may be due to floating point error, faulty logic, etc. 

I would like developers to be made aware of re-entrance during development, and for us to annotate all re-entrant Properties with `reentrant: true` so that maintainers will know that's an issue for that Property.  Using `?fuzzMouse`, I visited each sim and marked properties as `reentrant: true` as appropriate.  I had to mark 25 sites to get every simulation to pass fuzz mouse at least twice.  Bayes CT will probably pick up other cases that were missed during these fuzz sessions.  I think we should catch them as they come up and mark them as such.

Based on the results of this investigation, I'll commit my working copy changes, including changing Property's default to `reentrant: false` and the 25 occurrences of `reentrant: true` for specific Property instances.

For future steps, it would be nice to (a) add code comments to each re-entrant Property indicating why they are re-entrant, or (b) implement it without re-entrance.  I'll add a step to the code review document for that.

**Comment by samreid** [comment]
I commented on slack:

Sam Reid [9:40 AM]
I’ll be committing changes to a dozen or so repos to identify re-entrant properties as part of https://github.com/phetsims/axon/issues/179, please report any problems that you see.

Sam Reid [9:42 AM]
Pushes complete, please pull at your convenience.

**Comment by samreid** [comment]
@jonathanolson and I further discussed on slack:

Jonathan Olson [9:35 AM]
Fuzzing/CT is unlikely to catch some reentrant Properties that are hard to trigger (e.g. on correct completion of a game).


Sam Reid [9:36 AM]
Ah I see, good point.  Is QA now testing things with assertions?

Jonathan Olson [9:37 AM]
they might be testing debug versions, but might need the console open? not sure

Sam Reid [9:37 AM]
I think it’s still a good change to make.  It will be nice for us to catch re-entrance in corner cases like games ending.  We will catch those during development, and they will get stripped out during build, so it doesn’t seem too risky.

Jonathan Olson [9:38 AM]
Definitely understood and agreed. I might even suggest some deeper inspections/assertions, since I recall cases where “model” events could trigger “user” events. Is that type of thing checked right now?

Sam Reid [9:40 AM]
We don’t have a way set up to automatically catch those at the moment.  We could add something for that.  I think right now we’re just looking for that manually during PhET-iO design/implementation step.

**Comment by samreid** [comment]
@pixelzoom back to you for review, anything else to do here before closing?

**Comment by pixelzoom** [comment]
@samreid said:
> For future steps, it would be nice to (a) add code comments to each re-entrant Property indicating why they are re-entrant, or (b) implement it without re-entrance. I'll add a step to the code review document for that.

@samreid Should each of the repos where you explicitly set `reentrant: true`, should there be an issue to investigate and document why it's required, or reimplement? Without such an issue, what you've suggested will never happen.

**Comment by samreid** [comment]
> @samreid For each of the repos where you explicitly set reentrant: true, should there be an issue to investigate and document why it's required, or reimplement? 

I don't know.  That seems more a question for the team at large.

**Comment by pixelzoom** [comment]
I'm going to create such an issue for each of my sims.  Will leave this issue open to for developer meeting, so that others are aware and can decide what to do.

**Comment by pixelzoom** [comment]
Slack:

Chris Malley [10:56 AM]
More sims failing CT following the `reentrant: false` change. bending-light, gene-expression-essentials, masses-and-springs, ph-scale, wave-interference.  All reporting “Assertion failed: reentry detected”.

Sam Reid [10:57 AM]
Good to know, I’ll look into them.

**Comment by samreid** [comment]
I pushed fixes for those 5 repos and will check Bayes CT again in the future to see if something else comes up.

**Comment by pixelzoom** [comment]
As of 8/22/2018, 1:59:44pm, gravity-and-orbits is still failing with "Assertion failed: reentry detected" in CT.

**Comment by samreid** [comment]
I pushed a fix for the gravity and orbits problem that occurred on Bayes CT.

**Comment by samreid** [comment]
At today's meeting, we decided to create issues for the `reentrant: true` cases.  I'll tackle this.

**Comment by pixelzoom** [comment]
@samreid FYI, I believe that I've already created issues for all sims that I'm responsible for. E.g. https://github.com/phetsims/acid-base-solutions/issues/155.

**Comment by samreid** [comment]
Thanks @pixelzoom, I elevated priority to remind me to tackle this sooner rather than later.
